version: "3.7"

services:
  e2e-consumer:
    image: nethermind-e2e
    depends_on:
      - ndm-consumer
    environment:
      - JSON_RPC_URL=http://ndm-consumer:8545
    networks:
      - ndm
  
  ndm-consumer:
    build: .
    environment: 
      - NETHERMIND_CONFIG=ndm_consumer_e2e
      - NETHERMIND_JSONRPCCONFIG_HOST="0.0.0.0"
      - NDM_BACKGROUND_SERVICES_DISABLED=true
      - NDM_SENDING_DEPOSIT_TRANSACTION_DISABLED=false
      - NDM_INSTANT_DEPOSIT_VERIFICATION_ENABLED=true
    networks:
      - ndm
        
networks:
  ndm:
    name: ndm-network
