name: Publish Alpine Linux Image to Docker Registry

on:
  push:
    tags:
    - '*'

jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - name: Publish to Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        GIT_COMMIT: $(git log -1 --format=%h)
      with:
        name: nethermind/nethermind:alpine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        build-args: GIT_COMMIT
        dockerfile: Dockerfile_alpine