name: Discord release announcement

on:
  release:
    types: [published]

jobs:
  announce:
    name: Announce on Discord
    runs-on: ubuntu-latest
    steps:
    - name: Post announcement
      run: |
        read VERSION URL < <(echo $(curl -s 'https://api.github.com/repos/nethermindeth/nethermind/releases/latest' | jq -r '.name, .html_url'))
        MESSAGE="@everyone **Nethermind ${VERSION} is out!**\n\n${URL}"
        curl ${{ secrets.DISCORD_WEBHOOK_URL }} -X POST --fail-with-body -H "Content-Type: application/json" \
          -d '{"username": "Nethermind", "content": "'"$MESSAGE"'"}'
