name: '[RUN] Consensus legacy tests'

on:
  push:
    tags:
    - '*'

jobs:
  run-legacy-tests:
    name: Run blockchain tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
    - name: Installing Linux packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libsnappy-dev libc6-dev libc6
    - name: Ethereum.Blockchain.Block.Legacy
      run: |
        dotnet test -c release src/Nethermind/Ethereum.Blockchain.Block.Legacy.Test

  run-general-state-tests:
    name: Run general state tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8
    - name: Update submodules
      run: git submodule update --init
    - name: Ethereum.Blockchain.Legacy
      run: |
        dotnet test -c release src/Nethermind/Ethereum.Blockchain.Legacy.Test
