name: '[RUN] Hive Tests'
   
on: 
  push:
    tags:
    - '*'
    inputs:
      testSuite:
        description: 'Test suite'
        required: true
        default: 'ethereum/engine' 
        type: choice
        options:
        - ethereum/engine        
      limit:
        description: 'Limit for hive tests'
        required: false
        type: string
      hive:
        description: 'Repository for hive tests'
        required: true
        default: 'ethereum/hive'
        type: string        
      branch:
        description: 'Branch for hive tests'
        default: 'master'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      testSuite:
        description: 'Test suite'
        required: true
        default: 'ethereum/engine' 
        type: choice
        options:
        - ethereum/engine        
        - ethereum/rpc
        - devp2p
        - ethereum/graphql
        - ethereum/consensus
      limit:
        description: 'Limit for hive tests'
        required: false
        type: string        
      hive:
        description: 'Repository for hive tests'
        required: true
        default: 'ethereum/hive'
        type: string        
      branch:
        description: 'Branch for hive tests'
        default: 'master'
        required: false
        type: string

jobs:
  build-dockers:
    runs-on: ubuntu-latest
    steps:
      - name: Output Inputs
        env: 
            PARAMS_ENTERED: ${{ toJSON(github.event.inputs) }}
        run: echo $PARAMS_ENTERED
      - name: Checking out Nethermind
        uses: actions/checkout@v2
      - name: Unshallow fetching
        run: git fetch --unshallow
      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Building Nethermind Image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          tags: nethermind:test-${{ github.sha }}
          outputs: type=docker,dest=/tmp/image.tar
      - name: Installing Linux packages
        run: |
         sudo apt-get update
         sudo apt-get install libsnappy-dev libc6-dev libc6 build-essential
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
         go-version: '>=1.17.0'
      - name: Check out Hive
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.hive }}
          ref: ${{ github.event.inputs.branch }}
      - name: Change Hive configuration
        run: sed -i 's#FROM nethermindeth/hive:$branch#FROM nethermind:test-${{ github.sha }}#g' clients/nethermind/Dockerfile
      - name: Build Hive
        run: go build .
      - name: Load Docker Image
        run: docker load --input /tmp/image.tar
      - name: Run Hive
        if: "${{ github.event.inputs.limit == '' }}"
        run: ./hive --client nethermind --sim ${{ github.event.inputs.testSuite }}
      - name: Run Hive With Limit
        if: "${{ github.event.inputs.limit != '' }}"
        run: ./hive --client nethermind --sim ${{ github.event.inputs.testSuite }} --sim.limit ${{ github.event.inputs.limit }}
      - name: Upload Hive Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: workspace
          retention-days: 7
      - name: Move Results
        run: mv workspace /tmp
      - name: Set Up Python
        uses: actions/setup-python@v3
      - name: Checking out Nethermind
        uses: actions/checkout@v2        
      - name: Print Results
        run: python scripts/testing/hiveTestResultPrinter.py /tmp/workspace/logs/*.json
