name: Truffle smoke test

on:
  push:
    tags:
    - '*'

jobs:
  truffle-tests:
    name: Nethermind truffle tests on Spaceneth
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Installing Linux packages
      run: |
        sudo apt-get update
        sudo apt-get install libsnappy-dev libc6-dev libc6
    - name: Updating submodules
      run: git submodule update --init src/rocksdb-sharp src/int256 src/Dirichlet
    - name: Cloning truffle tests
      run: |
        git clone https://github.com/NethermindEth/truffleTest.git
    - name: Building nethermind docker
      run: docker build -t neth .
    - name: Setup the Node.js
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '13'
    - run: npm install -g truffle
    - name: Running truffle deploy & test
      run: |
        docker run --name nethermind --network host -itd neth --config spaceneth_persistent
        cd truffleTest/
        npm i sha3 --save
        npm i
        echo "silly funny task remove diamond maximum rack awesome sting chalk recycle also social banner verify" > .secret
        sleep 20
        truffle deploy --network development
        truffle test
