name: '[UPDATE] Config files (fast sync settings)'

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  
permissions:
  contents: write
  pull-requests: write

jobs:
  update-configs:
    if: github.repository_owner == 'NethermindEth'
    name: Update fast sync settings in config files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Install dependencies
        run: |
          pip3 install setuptools
          pip3 install emoji
      - name: Update config files
        run: |
          python3 scripts/syncSettings.py ${{ secrets.ETHERSCAN_API_KEY }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updating Fast Sync config files
          body: |
            Config files included: 
            - mainnet.cfg
            - goerli.cfg
            - rinkeby.cfg
            - sepolia.cfg

            Properties refreshed:
            - PivotNumber
            - PivotHash
            - PivotTotalDifficulty

            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          title: "Update Fast Sync configuration in Nethermind repository"
          labels: configs
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          committer: GitHub <noreply@github.com>
          branch: configs-update
          branch-suffix: short-commit-hash
          base: master
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
